dist: xenial

language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt --ignore-requires-python

script: python -m unittest

notifications:
  email:
    on_success: never
    on_failure: never
